### ISSUE TITLE
StatusField is not using get_status_display since Django 2.2.7

### ISSUE THREAD

**Issue by RaddishIoW** [jazzband/django-model-utils#399] opened 2019-11-13 16:10 UTC
## Problem

Since updating Django to 2.2.7, get_status_display() doesn't return the human readable string.

## Environment

- Django Model Utils version: 3.2.0
- Django version: 2.2.7
- Python version: 3.6
- Other libraries used, if any:

## Code examples
```
UNCONFIRMED_BOOKING = 'UNCB'
CONFIRMED_BOOKING = 'CONB'
ASSINGNED = 'ASSD'
ACTIVE = 'ACTV'
COMPLETED = 'COMP'
CANCELLED = 'CANC'

JOB_STATUS = (
    (UNCONFIRMED_BOOKING, _("Unconfirmed Booking")),
    (CONFIRMED_BOOKING, _("Confirmed Booking")),
    (ASSINGNED, _("Assigned")),
    (ACTIVE, _("Active")),
    (COMPLETED, _("Completed")),
    (CANCELLED, _("Cancelled"))
)

class Job(StatusModel):
    '''
    Model for jobs
    '''

    STATUS = statuses.JOB_STATUS
    status = StatusField(db_index=True)
```
In template:
```
<p><b>Current status:</b> {{job.get_status_display}} </p>
```
For a status of CONFIRMED_BOOKING displays "CONB" instead of "Confirmed Booking"

**Comment by Natim** [comment] 2019-12-09 16:30
Hello @RaddishIoW can you try that this issue is still present with Django 2.2.8 and Django 3.0?

**Comment by RaddishIoW** [comment] 2019-12-09 21:54
Just updated to 2.2.8 and I'm still seeing it.

I'll try with 3.0, if I can get my project to run with it!

**Comment by RaddishIoW** [comment] 2019-12-09 22:20
Some of my other dependancies don't yet work with Django 3.0 (django-registration-redux, among others), so I can't test against 3.0 unless I write a special test case project.

**Comment by RaddishIoW** [comment] 2019-12-31 18:26
Could do with updating to 2.2.8 ASAP, as there's a security warning against 2.2.5... Is there a workaround I could implement? How can I get the display text of the status in a template?

**Comment by Natim** [comment] 2020-01-03 10:39
@RaddishIoW could you start a PR with a failing test for your use case?

**Comment by Natim** [comment] 2020-01-03 10:41
I looked at the tests, what about using:

```
JOB_STATUS = (
    (UNCONFIRMED_BOOKING, "Unconfirmed Booking", _("Unconfirmed Booking")),
    (CONFIRMED_BOOKING, "Confirmed Booking", _("Confirmed Booking")),
    (ASSINGNED, "Assigned", _("Assigned")),
    (ACTIVE, "Active", _("Active")),
    (COMPLETED, "Completed", _("Completed")),
    (CANCELLED, "Cancelled", _("Cancelled"))
)
```

**Comment by Natim** [comment] 2020-01-03 10:47
I tried something like this: https://github.com/jazzband/django-model-utils/pull/409
Is this what you had in mind?

**Comment by Natim** [comment] 2020-01-03 10:50
I am not able to reproduce with this test: https://travis-ci.org/jazzband/django-model-utils/jobs/632236954

**Comment by RaddishIoW** [comment] 2020-01-03 14:36
Hi @Natim, I'm not using the Choices class, but a tuple list of choices... I don't know if that makes a difference? I'll upload a PR with a test when I get a chance.

**Comment by Natim** [comment] 2020-01-03 14:36
Good catch, I am going to try to update the test accordingly.

**Comment by RaddishIoW** [comment] 2020-01-03 14:57
OK, tried the Choices type as below, and still seeing the issue with Django 2.2.8.
```
STATUS = Choices((UNCONFIRMED_BOOKING, _("Unconfirmed Booking")),
                     (CONFIRMED_BOOKING, _("Booking")),
                     (ASSIGNED, _("Assigned")),
                     (ACTIVE, _("Active")),
                     (RUN_IN, _("Run In")),
                     (ARRIVED_AT_PICKUP, _("Arrived At Pickup")),
                     (POB, _("P.O.B")),
                     (COMPLETED, _("Completed")),
                     (CANCELLED, _("Cancelled"))
                     )
```

**Comment by Natim** [comment] 2020-01-03 15:48
The tests are still passing there: https://github.com/jazzband/django-model-utils/pull/409/commits/e4347a1426fbcdbfe7b5b1009daee3f29b6e963a

Really strange.

**Comment by RaddishIoW** [comment] 2020-01-03 21:10
I've written a test case in my code to check the return of `<instance>.get_status_display()` and it's showing the error in django=>2.2.7...

I found this bug marked as fixed in django 2.2.7 release notes: https://code.djangoproject.com/ticket/30931
which might be relevant?

I'm not sure at the moment why I can't reproduce this outside of my project, but I'll keep looking.

**Comment by RaddishIoW** [comment] 2020-01-09 12:10
To update this, I'm still seeing this issue with Django 3.0.2 after updating.

I'm wondering if it would be worth me giving temporary access to my code for you to look at the issue "in situ", rather than abstracting it into a test case? There's clearly something particular about my setup that we're not replicating in the test, but I can't immediately see what it could be.

**Comment by RaddishIoW** [comment] 2020-01-24 12:01
I've managed to replicate this issue in the test case (see my pull request #410 ).

I've changed my code so that my class no longer inherits from StatusModel, and instead includes StatusField and MonitorField directly.
Is this the correct way to do this? If so, would it be worth explaining somewhere that if you need to override the StatusField, not to inherit from StatusModel, but implement the two fields directly?

**Comment by robspare** [comment] 2021-04-22 13:00
Experiencing the same problem. I've added a failing test which illustrates this problem in #488. @Natim, please review and let me know if you have further questions. Look forward to getting a fix for this as we are experiencing this issue in production at Django 2.2 with no current plans to upgrade to 3.x.

**Comment by foarsitter** [comment] 2024-03-25 07:29
Played around with #488 and this is no longer an issue.

**Closed by foarsitter** 2024-03-25 07:29 UTC
Labels: bug, module: choices
