### ISSUE TITLE
__init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by erikcw** [jazzband/django-model-utils#346] opened 2018-11-08 19:58 UTC
## Problem
```
Template error:
In template /Users/erik/Dropbox/home/git/crm/templates/crm/base.html, error at line 119
   __init__() takes 2 positional arguments but 3 were given
   111 : 
   112 :     </div> <!-- /container -->
   113 : 
   114 :     <!-- Le javascript
   115 :     ================================================== -->
   116 :     <!-- Placed at the end of the document so the pages load faster -->
   117 :     {% block javascript_includes %}
   118 :     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   119 :     <link rel="stylesheet" type="text/css" href="//cd njs.cloudflare.com/ajax/lib s/select2/3.5.2/select2.css" />
   120 :     <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.js"></script>
   121 :     {% endblock javascript_includes %}
   122 :     {% block end_body %}
   123 :     {% endblock end_body %}
   124 :     {% include "portal/sudo_exit_include.html" %}
   125 :   </body>
   126 : </html>
   127 : 

Traceback:

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  156.                 response = self.process_exception_by_middleware(e, request)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  154.                 response = response.render()

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/response.py" in render
  106.             self.content = self.rendered_content

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/response.py" in rendered_content
  83.         content = template.render(context, self._request)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  166.             len_values = len(values)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/query.py" in __len__
  250.         self._fetch_all()

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/query.py" in _fetch_all
  1186.             self._result_cache = list(self._iterable_class(self))

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/query.py" in __iter__
  66.                 rel_populator.populate(row, obj)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/query.py" in populate
  1829.                 rel_iter.populate(row, obj)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/query.py" in populate
  1827.             obj = self.model_cls.from_db(self.db, self.init_list, obj_data)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/base.py" in from_db
  497.         new = cls(*values)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/db/models/base.py" in __init__
  487.         post_init.send(sender=cls, instance=self)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/dispatch/dispatcher.py" in send
  175.             for receiver in self._live_receivers(sender)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/django/dispatch/dispatcher.py" in <listcomp>
  175.             for receiver in self._live_receivers(sender)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/model_utils/tracker.py" in initialize_tracker
  163.         tracker = self.tracker_class(instance, self.fields, self.field_map)

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/model_utils/tracker.py" in __init__
  37.         self.init_deferred_fields()

File "/Users/erik/.virtualenvs/crm/lib/python3.7/site-packages/model_utils/tracker.py" in init_deferred_fields
  112.                         field_obj.field_name, None)

Exception Type: TypeError at /portal/reports/
Exception Value: __init__() takes 2 positional arguments but 3 were given
```

## Environment

- Django Model Utils version: 3.8.2
- Django version: 2.1.3
- Python version: 3.6 and 3.7
- Other libraries used, if any:

## Code examples

Removing FieldTracker() from my models fixes the exception.

**Comment by robertobarreda** [comment] 2018-11-29 14:36
Solved in #334

**Comment by surenkov** [comment] 2018-12-11 19:04
Old `model` parameter, kept for compatibility purposes, has been removed from `DeferredAttribute.__init__()` signature in Django 2.1.

**Comment by aidanlister** [comment] 2018-12-26 19:58
@surenkov so django-model-utils not compatible with latest Django?

**Comment by aidanlister** [comment] 2018-12-28 20:56
Duplicate of https://github.com/jazzband/django-model-utils/issues/333

**Comment by kanemra** [comment] 2019-01-09 16:01
Do you know release date?

**Closed** 2019-02-21 19:10 UTC
